/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ran_ben_androidcomponentdemo_utils_NdkJniUtils */

#ifndef _Included_com_ran_ben_androidcomponentdemo_utils_NdkJniUtils
#define _Included_com_ran_ben_androidcomponentdemo_utils_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ran_ben_androidcomponentdemo_utils_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_ran_ben_androidcomponentdemo_utils_NdkJniUtils_checkDexMD5
        (JNIEnv* env,
         jobject thiz, jobject application, jstring file);

#ifdef __cplusplus
}
#endif
#endif
